### ISSUE TITLE
Should we add package-lock.json in gitignore? 

### ISSUE THREAD

**Issue by reeversedev** [Grommerce/grommerce-frontend#18]
Found this link online, so I don't think it's be a great idea to package-lock.json in regular commits. 

https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Please enlighten me about your experiences and suggestions.

**Comment by mariolo1985** [comment]
Hi - sorry again to intrude. This is just my opinion so take it lightly. I like committing my lock file so you can quickly tell a module was updated. If I pull to local and the lock file is different than I know to re-install my modules. This will be helpful when you have contributors outside your org submitting updates to ensure they are installing the correct dependencies.

**Comment by reeversedev** [comment]
@mariolo1985 Interesting and I think that is one of the pros that package-lock has. +1 for this.

**Comment by reeversedev** [comment]
It seems like, everyone agrees that we should not put package-lock.json in gitignore since it is important for tracking of installation of packages.

So, I am closing this issue.
