### ISSUE TITLE
Create an inventory page

### ISSUE THREAD

**Issue by bhautikbharadava** [Grommerce/grommerce-frontend#44]
**Describe the solution you'd like**
An inventory page which contains table of available items with edit option on it. There will be a search bar to search items from the table. Also, there will be a button to add a new item.

**Additional context**
Refer link for wireframe https://wireframe.cc/QC9LVv

**Comment by reeversedev** [comment]
Since, it's just exactly like 'All Products' page, I am marking it as done.
