### ISSUE TITLE
Proposed design for Login form

### ISSUE THREAD

**Issue by plxity** [Grommerce/grommerce-frontend#52]
![Capture](https://user-images.githubusercontent.com/28510494/55349955-8c002680-54d8-11e9-849c-104f19c81e67.PNG)

@bhautikbharadava @reeversedev What do you guys think about this design?
Any feedback?

**Comment by plxity** [comment]
@plxity Okay, I will try.

**Comment by plxity** [comment]
![Capture](https://user-images.githubusercontent.com/28510494/55401385-30807800-556e-11e9-803c-5fdb4bae48b8.PNG)
@reeversedev How about this?

**Comment by reeversedev** [comment]
Yeah this looks much better. Can we start coding this or you need more time to work on this?

**Comment by plxity** [comment]
I think I should improve this a bit.

**Comment by reeversedev** [comment]
Cool take your time.

**Comment by bhautikbharadava** [comment]
Adding  shadow to the card will make it more interesting. 
Move content vertically center of the shape.
I would recommend you to create whole screen and make some arrangements to spacing also.
Also think about signup screen . As generally it will be same as login page.

**Comment by bhautikbharadava** [comment]
I think we are creating store designs so move issue to there also.

**Comment by plxity** [comment]
@bhautikbharadava Okay, I will make the following changes.

**Comment by plxity** [comment]
I will upload the final design by night. 😃

**Comment by plxity** [comment]
![Capture](https://user-images.githubusercontent.com/28510494/55684429-fe08bd80-5967-11e9-95d6-1344e3bc7a9a.PNG)
@reeversedev @bhautikbharadava What do you think about this design?

**Comment by reeversedev** [comment]
@plxity Excellent approach! But can you try and reduce the shadow a bit and I think we can finalise after that. I liked the design without any design specially from a guy who's not even a core designer yet. Keep doing it, I think you have the UX sense. 

If you think, this particular design can be improved, then do it.

**Comment by plxity** [comment]
@reeversedev Thank you so much. :)
I will make the changes, so that we can finalize the design by today and begin with the implementation

**Comment by reeversedev** [comment]
Sure!
