### ISSUE TITLE
Fixed routing problem happening because of webpack configuration

### ISSUE THREAD

**Issue by reeversedev** [Grommerce/grommerce-frontend#56]
Need to change the webpack config to handle the routing

**Comment by reeversedev** [comment]
@meetzaveri Can you check if this is a correct way of doing thing? 

As far as I have tested, this works absolutely fine.

**Comment by meetzaveri** [comment]
Sure I'll check it out and let you know tommorow or asap

**Comment by meetzaveri** [comment]
Was this issue coming in prod build?

**Comment by reeversedev** [comment]
No, this issue was in development mode.

**Comment by meetzaveri** [comment]
Okay. I took pull and checked the code.Looks good to me

**Comment by meetzaveri** [comment]
Also config looks more cleaner now

**Comment by reeversedev** [comment]
Okay. Should I close it then? Everything looks fine to me as well.

**Comment by meetzaveri** [comment]
Yes sure, way to go
