### ISSUE TITLE
Add a product page to show information related to it

### ISSUE THREAD

**Issue by reeversedev** [Grommerce/grommerce-frontend#57]
It should look something like this: 

![Screenshot 2019-08-21 at 1 11 11 AM](https://user-images.githubusercontent.com/21155917/63378845-b469be00-c3b0-11e9-8d32-2337a8d44f66.png)

**Comment by reeversedev** [comment]
This page should ideally focus on the name, description, brand, tags, orders and sales analytics.

**Comment by meetzaveri** [comment]
Is someone working on this @reeversedev ?

**Comment by reeversedev** [comment]
I assigned it to myself. You wanna work on this?

**Comment by meetzaveri** [comment]
Oh got it. Is there any other module I can take on?

**Comment by reeversedev** [comment]
You can take this one if you want. I really want some time to decide further modules.

**Comment by reeversedev** [comment]
This is done, so closing it.
