### ISSUE TITLE
Travis CI is always throwing a build error even when everything works fine

### ISSUE THREAD

**Issue by reeversedev** [Grommerce/grommerce-frontend#58]
**Describe the bug**

After testing the code myself, I am able to see that Travis CI checks two times. While it passes in first go, it fails in the next.

**To Reproduce**

Honestly, I don't know what's wrong here maybe the .yml file that we created lacks something or maybe it's the issue with compatibility of environment.

**Expected behavior**

It should pass after check

**Screenshots**

![Screenshot 2019-08-21 at 11 41 35 AM](https://user-images.githubusercontent.com/21155917/63406871-c7a87800-c408-11e9-8454-7f5525bc77c2.png)

**Comment by reeversedev** [comment]
@meetzaveri Can you take this?

**Comment by meetzaveri** [comment]
Sure. Let me debug then

**Comment by meetzaveri** [comment]
@reeversedev  Can you help me with that ? Like does github detect if there is a new commit then to run travis build ? If yes then which is the config file required for it ?

**Comment by meetzaveri** [comment]
I might have find a solution. Is `iojs` version required for node_js as in for build process ? Most of the modern Open source organizations like FOSSASIA or Formidable labs are not using `iojs`. So should we eliminate that version from node_js version in `travis.yml` ?

Formidable labs travis config - https://github.com/FormidableLabs/victory/blob/master/.travis.yml

**Comment by meetzaveri** [comment]
Also I think we should upgrade our travis config. I read this article and it's very helpful - https://www.diycode.cc/projects/ruanyf/travis-ci-demo

**Comment by reeversedev** [comment]
I am assigning it to you then.

**Comment by reeversedev** [comment]
This is fixed in #61 . Hence closing it for now.
