### ISSUE TITLE
Setup of Jest for writing test cases.

### ISSUE THREAD

**Issue by reeversedev** [Grommerce/grommerce-frontend#6]
We need to write test cases for a stable project. As of now, I don't have enough experience for writing test cases so I am putting this issue in 'help wanted' category.

**Comment by mariolo1985** [comment]
Hey @reeversedev sorry to intrude. I was searching around for `help-wanted` issues and landed here. I have a few Jest test for React components [here](https://github.com/mariolo1985/init-react-redux/tree/master/src/components/Menu/components) if you want to look at some examples. 

What type of Jest tests will you need?

**Comment by reeversedev** [comment]
Hey @mariolo1985 ,
Honestly, We are not experienced with writing test cases specially in Jest. It's new for us and we are more likely exploring it.
We need testing for React Components first, then as we are building our application on the foundation of GraphQL, then writing test cases for that will also be needed.

**Comment by mariolo1985** [comment]
@reeversedev it's great that you are thinking of unit testing so early on. I am not very experience with writing test either. It is a new concept to me and something I am slowly exploring. From the little experience I have, I feel the time invested is well returned. With an application like yours that have front-end and back-end parts, it will be helpful to validate the interactions and responses.
